import { ContactMech, Enumeration, Geo, Party, Status, Uom } from "./index"

export interface Facility {
  facilityId: string,
  pseudoId?: string,
  facilityTypeEnumId?: string,
  parentFacilityId?: string,
  statusId?: string,
  ownerPartyId?: string,
  facilityName?: string,
  facilitySize?: 0,
  facilitySizeUomId?: string,
  openedDate?: string,
  closedDate?: string,
  description?: string,
  geoId?: string,
  geoPointId?: string,
  countyGeoId?: string,
  stateGeoId?: string,
  assetAllowOtherOwner?: string,
  assetAllowIssueOverQoh?: string,
  assetInventoryLocRequire?: string,
  defaultDaysToShip?: 0,
  externalId?: string,
  originId?: string,
  type?: Enumeration,
  parent?: Facility,
  status?: Status,
  owner?: Party,
  sizeUom?: Uom,
  geo?: Geo,
  geoPoint?: {
    geoPointId?: string,
    geoPointTypeEnumId?: string,
    description?: string,
    dataSourceId?: string,
    latitude?: 0,
    longitude?: 0,
    elevation?: 0,
    elevationUomId?: string,
    information?: string
  },
  certifications?: Array<{
    facilityCertificationId?: string,
    facilityId?: string,
    certificationTypeEnumId?: string,
    fromDate?: string,
    thruDate?: string,
    contactPartyId?: string,
    auditorPartyId?: string,
    auditorOrgPartyId?: string,
    auditStartDate?: string,
    auditEndDate?: string,
    auditScore?: string,
    certRegistrationId?: string,
    otherCertId?: string,
    documentLocation?: string,
  }>,
  contactMechs?: Array<{
    facilityId?: string,
    contactMechId?: string,
    contactMechPurposeId?: string,
    fromDate?: string,
    thruDate?: string,
    extension?: string,
    comments?: string,
    contactMech?: ContactMech,
    purpose?: {
      contactMechPurposeId?: string,
      contactMechTypeEnumId?: string,
      description?: string,
    }
  }>,
  groups?: Array<{
    facilityId?: string,
    facilityGroupId?: string,
    fromDate?: string,
    thruDate?: string,
    sequenceNum?: 0,
    group?: {
      facilityGroupId?: string,
      parentGroupId?: string,
      facilityGroupTypeEnumId?: string,
      description?: string,
    }
  }>,
  notes?: Array<{
    facilityId?: string,
    noteDate?: string,
    userId?: string,
    noteText?: string,
  }>,
  parties?: Array<{
    facilityId?: string,
    partyId?: string,
    roleTypeId?: string,
    fromDate?: string,
    thruDate?: string,
    party?: Party,
    role?: {
      roleTypeId?: string,
      parentTypeId?: string,
      description?: string,
    }
  }>
}